import React, { useEffect } from 'react';
import { Shield, Key, Lock, RefreshCw } from 'lucide-react';
import { PasswordGenerator } from '@/components/PasswordGenerator';

export default function PasswordGeneratorPage() {
  useEffect(() => {
    document.title = "Free Password Generator - Strong & Secure Passwords | TempConnect";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute("content", "Generate strong and secure passwords instantly. Free online password generator with custom options for length, symbols, numbers, and more.");
    }
  }, []);

  return (
    <div className="space-y-12">
      {/* Hero Section */}
      <section className="text-center space-y-4 mb-8">
        <h1 className="text-3xl md:text-4xl font-bold uppercase tracking-widest text-primary glitch" data-text="Free Password Generator">
          Free Password Generator
        </h1>
        <p className="text-muted-foreground max-w-2xl mx-auto text-sm md:text-base">
          Create strong, secure, and random passwords instantly to protect your online accounts from hackers and data breaches.
        </p>
      </section>

      {/* The Tool */}
      <section className="mb-12">
        <PasswordGenerator />
      </section>

      {/* SEO Content Section */}
      <section className="space-y-12 border-t border-border/50 pt-12">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div className="border-l-2 border-primary pl-4 py-1 bg-primary/5">
              <h2 className="text-xl font-bold uppercase tracking-widest text-primary">
                Why Use a Password Generator?
              </h2>
            </div>
            <div className="text-muted-foreground space-y-4 text-sm leading-relaxed">
              <p>
                In an era where data breaches and cyber attacks are increasingly common, your password is often the only line of defense between hackers and your personal information. A weak password like "password123" or your pet's name can be cracked in seconds using automated brute-force tools.
              </p>
              <p>
                Using a strong, random password generated by our tool ensures that your accounts remain secure. By combining uppercase letters, lowercase letters, numbers, and symbols, you create a cryptographic barrier that is virtually impossible for attackers to guess or crack.
              </p>
              <p>
                The main benefits of using random passwords include protection against dictionary attacks, credential stuffing, and social engineering. When you use a truly random string of characters, you eliminate the human predictability that hackers rely on.
              </p>
            </div>
          </div>

          <div className="space-y-6">
            <div className="border-l-2 border-primary pl-4 py-1 bg-primary/5">
              <h2 className="text-xl font-bold uppercase tracking-widest text-primary">
                How It Works
              </h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="bg-muted/10 border border-border p-4 space-y-2">
                <RefreshCw className="h-6 w-6 text-primary" />
                <h3 className="font-bold text-sm uppercase tracking-wider">True Randomness</h3>
                <p className="text-xs text-muted-foreground">Our algorithm uses secure random number generation to ensure unpredictable results.</p>
              </div>
              <div className="bg-muted/10 border border-border p-4 space-y-2">
                <Shield className="h-6 w-6 text-primary" />
                <h3 className="font-bold text-sm uppercase tracking-wider">Client-Side Only</h3>
                <p className="text-xs text-muted-foreground">Passwords are generated entirely in your browser. We never send or store your passwords on our servers.</p>
              </div>
              <div className="bg-muted/10 border border-border p-4 space-y-2">
                <Key className="h-6 w-6 text-primary" />
                <h3 className="font-bold text-sm uppercase tracking-wider">Customizable</h3>
                <p className="text-xs text-muted-foreground">Tailor the length and character types to meet the specific requirements of any website.</p>
              </div>
              <div className="bg-muted/10 border border-border p-4 space-y-2">
                <Lock className="h-6 w-6 text-primary" />
                <h3 className="font-bold text-sm uppercase tracking-wider">Ambiguity Filter</h3>
                <p className="text-xs text-muted-foreground">Optionally exclude look-alike characters (like 'l' and '1') to make passwords easier to read and type.</p>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="border-l-2 border-primary pl-4 py-1 bg-primary/5">
            <h2 className="text-xl font-bold uppercase tracking-widest text-primary">
              Best Practices for Secure Passwords
            </h2>
          </div>
          <div className="text-muted-foreground space-y-4 text-sm leading-relaxed bg-muted/5 p-6 border border-border">
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Never reuse passwords:</strong> If one service is compromised, attackers will try that same password on your email, banking, and social media accounts. Use a unique, generated password for every service.</li>
              <li><strong>Length matters:</strong> A 16-character password is exponentially harder to crack than an 8-character one, even if both use complex symbols. Aim for at least 12-16 characters for important accounts.</li>
              <li><strong>Use a password manager:</strong> Since you shouldn't memorize dozens of complex random passwords, use a reputable password manager to store them securely.</li>
              <li><strong>Enable Two-Factor Authentication (2FA):</strong> Even the strongest password can be stolen through phishing. Always enable 2FA (like SMS codes or authenticator apps) for an extra layer of security.</li>
            </ul>
            <div className="mt-6 pt-4 border-t border-border/50">
              <p className="text-primary/80 italic">
                Looking for more privacy tools? Try also our <a href="/receive-sms" className="text-primary hover:underline font-medium">Receive SMS</a> tool for temporary phone numbers, or our <a href="/gerador-cpf-cnpj" className="text-primary hover:underline font-medium">CPF/CNPJ Generator</a> for software testing.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
